### ISSUE TITLE
Parsing a list of numbers

### ISSUE THREAD

**Issue by ayberkt** [kframework/plutus-core-semantics#1]
The two sample programs in `test`, `int-addition.plcore` and `float-addition.plcore` fail to kast. The issue seems to be that the list delimiter is a single space as defined in
```
  syntax TmList     ::= List{Tm,  " "}
```
which causes an ambiguity when combined with the regular expression for `Float`s.

For example, parsing the following expression
```
(builtin addFloat (2.0))
```
results in an ambiguity between
```
__(#token(Float@FLOAT-SYNTAX,"2.0"),.List{"__"}())
```
and
```
__(#token(Integer@PLUTUS-CORE-SYNTAX,"2"),__(#token(Float@FLOAT-SYNTAX,".0"),.List{"__"}()))
```

Help would be appreciated.

/cc: @msaxena2 @cos @daejunpark @radumereuta

**Comment by cos** [comment]
@radumereuta knows this much better.

My thoughts at a quick glance: are plutus integer different from the builtin ones? I would guess this issue appeared with the builtin ones as well. Have a look at that and see how it was disambiguated. There is likely some priority annotation saying that `Float@FLOAT-SYNTAX` has higher priority than `Int@INT-SYNTAX` and/or `__`.

**Comment by ayberkt** [comment]
@cos thanks for the suggestion! Now we have switched to using just the built-in K sorts i.e., we are just using the `Int` sort but we are still experiencing the same problem. This, however, at least fixed the parsing of a list of integers.

**Comment by radumereuta** [comment]
Is this language whitespace sensitive? Because if not, you can remove the spaces as delimiter from all the lists. You can just write:
```
 syntax TmList     ::= List{Tm,  ""}
```
and you will get the expected behavior. The spaces between lists will be discarded automatically during parsing time.

You also may want to have a look at follow and precede restrictions for the default builtin sorts (Int and Id). There are some cases when you may be able to remove some ambiguities with those.

Please let me know if you manage to solve those issues.
