### ISSUE TITLE
what's the relationship between plutus-core and plutus

### ISSUE THREAD

**Issue by clojurians-org** [kframework/plutus-core-semantics#41]
it seems the plutus-core is more lisp-style, so is it the AST syntax tree of haskell-styled plutus?
so how the plutus will turn into plutus-core?
 it seems exist too much compile step for running on iele?
marlowe->plutus->plutuscore->(iele->k->ocamel)?

**Comment by lucaspena** [comment]
Plutus Core is the core language of Plutus, similar to how Haskell has a core language as well. Like in Haskell Plutus programs will translate to programs in Plutus Core. That's a compilation step we're not focusing on in this work, but refer to the IOHK implementation of Plutus (https://github.com/input-output-hk/plutus-prototype/) for more details.

As far as the long-term plan for Plutus, it is as yet not clear whether it will be running on the EVM or on IELE. A translation to IELE provides the option for running it on IELE, as well as provides a lot of potential for verification, since Plutus Core, the translation, and IELE are all defined in K. In the long-term, we plan on using K's verification engine to prove correctness of this translation. As far as too many compile steps, many real-world programming languages have many more compile steps than this. As long as optimizations are done along the way, the amount of compile steps should not be a big problem.
